# ======================================
# Ruff configuration
# ======================================

line-length = 80
target-version = "py310"

# Автофиксы
fix = true
show-fixes = true

# ======================================
# Lint rules
# ======================================

[lint]
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
]

ignore = [
    "E501", # line too long — правим осознанно
]

# ======================================
# Django / project specifics
# ======================================

exclude = [
    ".git",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    "migrations",
    "staticfiles",
    "media",
]

# ======================================
# isort
# ======================================

[lint.isort]
known-first-party = [
    "task_manager",
    "task_manager_app",
]
combine-as-imports = true